[package]
name = "upbit-bot"
version = "0.1.0"
authors = ["ben.jung <ben.jung@kakaocommerce.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
bigdecimal = { version = "0.2", features = ["serde"] }
async-trait = "0.1"
anyhow = "*"
thiserror = "1"
dotenv = "0.15"
